### ISSUE TITLE
Mistranslation in 3.6 Git Branching - Rebasing

### ISSUE THREAD

**Issue by cdpark0530** [progit/progit2-ko#111]
In the section `Rebase When You Rebase`
Original Scripts:
`Determine what work is unique to our branch (C2, C3, C4, C6, C7)`
`Determine which are not merge commits (C2, C3, C4)`
`Determine which have not been rewritten into the target branch (just C2 and C3, since C4 is the same patch as C4')`
`Apply those commits to the top of teamone/master`

Korean Scripts:
- 현재 브랜치에만 포함된 커밋을 찾는다. (C2, C3, C4, C6, C7)
- Merge 커밋을 가려낸다. (C2, C3, C4)
- 이 중 덮어쓰지 않은 커밋들만 골라낸다. (C2, C3. C4는 C4’와 동일한 Patch다)
- 남은 커밋들만 다시 teamone/master 바탕으로 커밋을 쌓는다.

Wrong parts:
- 현재 브랜치에만 포함된 커밋을 찾는다. (C2, C3, C4, C6, C7)
현재 브랜치에만 포함된 커밋을 **결정한다**. (C2, C3, C4, C6, C7)
- Merge 커밋을 가려낸다. (C2, C3, C4)
Merge 커밋**이 아닌 것을 결정한다**. (C2, C3, C4)
- 이 중 덮어쓰지 않은 커밋들만 골라낸다. (C2, C3. C4는 C4’와 동일한 Patch다)
이 중 **merge할 브랜치에 덮어쓰이지** 않은 **커밋들을 결정한다**. (C2, C3. C4는 C4’와 동일한 Patch다)
- 남은 커밋들만 다시 teamone/master 바탕으로 커밋을 쌓는다.
**그 커밋들을 teamone/master에 적용한다**.

**Comment by pismute** [comment]
안녕하세요. 먼저 참여해주셔서 감사합니다.

이제는 잘 기억나지 않습니다. 하지만, 전체적으로 국문법이나 오역을 두려워하기 보다는 우리말스럽게 변역하려고 노력했습니다. 능력이 모자라 정 안되겠으면 그냥 영문표현을 썻습니다. Merge 처럼 말입니다. 많이 모자랐지만, 수동형는 능동형으로, 가능하면 우리말에 어울리는 동사와 부사를 선택하려고 애썼었습니다.--;

`결정한다`와 `적용한다`는 지양 했던 것 같습니다. 예를 들어, 의지나 취향을 가지고 선택지 중에서 하나를 고르는 것이라면 `결정한다`가 나을 것이지만, Git은 어떤 판단을 하는 것이 아니기 때문에 다른 표현을 선택했었을 것 같습니다. 마찮가지로 `적용한다`도 그렇습니다. 제 생각에는 Git에서 Apply를 `적용`으로 번역하면 의미가 불분명합니다. 이런 경우 좀 더 구체적인 표현을 찾거나 그냥 `Apply 한다`라고 했었던 것 같습니다. `적용(Apply)`처럼 병기하는 것도 피했었습니다.

`Merge 커밋을 가려낸다.`는 명백한 오역이군요. `Merge 커밋이 아닌 것을 가려낸다.`라고 했었어야 했는데. 나중에 누군가 원문을 고쳤을 것이라고 믿고 싶네요.--;

물론 관사와 복수도 지양 했습니다. 물론 여기저기 아직 많이 남아있습니다. `그 커밋들`에서 `그` 대신 좀 더 구체적인 표현으로 `남은`을 골랐을 것입니다. `커밋들`에서 `들`도 떼어 버렸어야 했는데 남아 있네요.

그리고 PR로 부탁드립니다.

**Comment by cdpark0530** [comment]
@pismute 
아 번역하신 분인가 보네요! 덕분에 git를 좀 더 빠르게 배울 수 있었습니다.

우리말에 어울리는 단어들과 복수를 단수로 표현하는 것, 저도 대학교 다닐 때까지는 그게 맞다고 생각하고 그렇게 사용해왔었는데, 영어가 익숙해진 순간부터 최소한 전문적인 문서를 번역하거나 읽을 때 그게 혼동을 가져다준다는 걸 경험하고 있습니다.

해당 원문은 git가 rebase 수행 시에 각 단계에서 **어떤 동작들을 수행하는가**가 아니라 **어떤 결과를 도출하는가**를 설명한 것입니다. 독자의 입장에서도 각 단계의 결과가 무엇인지 설명하는 것이 무슨 동작을 수행하는지 설명하는 것보다 직관적이고, 또 해당 내용을 읽는 목적을 고려했을 때도 합리적인 방법입니다. 그래서 원문에도 find나 select따위의 동사들을 사용하지 않고 apply와  determine 따위의 동사들을 사용한 것입니다.

마지막으로 복수를 단수형으로 치환하는 번역은 피해주셨으면 합니다. 여느 전문적인 문서와 같이 git를 설명하는 해당 문서도 일상생활에 대한 것이 아닌 논리적인 명세이기 때문에 복수형을 단수형으로 써서는 안 됩니다.
