### ISSUE TITLE
2.6 Git의 기초 - 태그 오타

### ISSUE THREAD

**Issue by gwonhong** [progit/progit2-ko#117]
https://git-scm.com/book/ko/v2/Git%EC%9D%98-%EA%B8%B0%EC%B4%88-%ED%83%9C%EA%B7%B8

마지막 "태그를 Checkout 하기" 에서
"새로운 커밋이 하나 쌓이 상태가 되고"라는 사소한 오타가 있습니다.
쌓이 -> 쌓인 으로 수정이 필요할 것 같습니다.

**Comment by lethee** [comment]
수정했습니다. 감사합니다.
