### ISSUE TITLE
백틱, 따옴표 관련 문제

### ISSUE THREAD

**Issue by eggmoid** [progit/progit2-ko#124]
영문판에서는 단어 강조할 때 사용하는 부호를 큰따옴표를 사용해서 “단어“같은 형식으로 나타내는데, 한글 번역판에서는 앞에는 백틱, 뒤에는 작은따옴표를 사용해서 ``단어'' 같은 형식으로 나타내는 것으로 보입니다.

한 문장에 저렇게 강조된 단어가 하나만 나오는 글의 경우에는 문제없이 출력이 되지만, 저런 게 두 개 이상 나오는 글의 경우에는 Asciidoc에서 Quoted Text로 취급되어서 중간 단어가 이상하게 표시되는 문제가 있습니다.

아래는 그 예시입니다.
![image](https://user-images.githubusercontent.com/16630665/145664932-54ac187f-7d08-45cb-83ec-aae97ac1adca.png)
[영문판](http://git-scm.com/book/en/v2/Git-on-the-Server-GitLab)
![image](https://user-images.githubusercontent.com/16630665/145664953-4a361b57-f9f0-4c20-8da6-4ae0288d6623.png)
[번역판](http://git-scm.com/book/ko/v2/Git-%EC%84%9C%EB%B2%84-GitLab)

혹시 백틱을 사용하는 특별한 이유가 있을까요?
특별한 이유가 없다면 해당 내용으로 PR 작성해도 되는지 궁금합니다. (백틱+작은따옴표로 작성된 내용이 많아서 전부 작은따옴표+작은따옴표 형식으로 바꿨더니 61개 파일이나 변경사항이 생기는데, 이렇게 많은 내용을 한 번에 작성해도 되는지 궁금합니다.)

**Comment by lethee** [comment]
한글판에서는 예전방식으로 작성되어있고 따옴표로 바뀐 것이 얼마 안되었는데 PDF로 변환되는 내용을 확인하고 고치도록 하겠습니다.

**Comment by pismute** [comment]
fixed by #125
