### ISSUE TITLE
인라인 역주 포맷 정하기

### ISSUE THREAD

**Issue by lnyarl** [progit/progit2-ko#17]
역주를 달려다가 보니 1판의 역주는 아래와 같이 여러가지가 섞여 쓰였습니다.
>(역주, XXX)
>(역주 : XXX)
>(역주 - XXX)

이것을 하나로 통일해야 하는게 좋을 것 같습니다. 전 모든 챕터가 번역된 뒤에 한번에 바꾸는게 좋을것 같은데 다른 의견 있으시면 포스팅 부탁드립니다.

**Comment by pismute** [comment]
(역주 - XXX) :+1:
