### ISSUE TITLE
용어 정리

### ISSUE THREAD

**Issue by pismute** [progit/progit2-ko#20]
1판에서도 줄 곧 통일시켜왔는데, 다시보니 아직도 흐트러져 있습니다.
언제 한 번 정리해야 합니다.

- [ ] Workflow -> 워크플로우
- [x] 패치 -> Patch
- [x] 댓글 -> 코멘트

**Comment by lethee** [comment]
* Repository - 저장소
* Remote - 리모트
* Commit - 커밋

**Comment by lnyarl** [comment]
영어를 그대로 쓰는것도 적습니다.
 - rebase - Rebase
 - push - Push
 - git - Git(프로그램을 의미할 때), git(명령어를 의미할 때)

**Comment by pismute** [comment]
오 @lnyarl 같은 영웅님을 기다렸습니다. 미리 감사드립니다.

**Comment by lnyarl** [comment]
- version-control - 버전 컨트롤

껀수가 나올때마다 하나씩 달껍니다.

**Comment by lethee** [comment]
버전 관리 한표요

**Comment by pismute** [comment]
버저관리 +1

**Comment by lnyarl** [comment]
버전관리 + 1

2015-04-09 0:14 GMT+09:00, Changwoo Park <notifications@github.com>:
> 버저관리 +1
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/progit/progit2-ko/issues/20#issuecomment-90946736


-- 
- 최용재
- mage
- lnyarl

**Comment by lnyarl** [comment]
- bundle - bundle(명령어일때), Bundle(번들로 만들어진 파일이나 그 개념을 나타낼때)

**Comment by pismute** [comment]
사이트->싸이트
스레드->쓰레드

나는 `싸이트, 쓰레드`로 했지만, 우리말배움터는 자꾸 `사이트, 스레드`로 추천해줘서 고민입니다.
`사이트, 스레드` 매우 어색하지 않나요?

**Comment by lnyarl** [comment]
- username - 사용자 이름
 - password - 비밀번호

**Comment by lnyarl** [comment]
- helper - helper
 - upstream - upstream

**Comment by pismute** [comment]
- 기관 - Organization: 6장에서, Organization을 굳이 번역하지 않으려 했는데, 번역한 곳이 있음.

**Comment by lnyarl** [comment]
- Windows - 윈도우즈. 우리말 배움터에서는 계속 윈도즈 라고 쓰라고 뭐라 그래서-_- 명시해둡니다.
 - Mac - 맥(?)

**Comment by pismute** [comment]
Windows의 한글 표기는 '윈도'이고, 1판에서도 '윈도'라고 표기했습니다. 찾아보니 빠트린 곳도 있네요.

**Comment by lnyarl** [comment]
헉 그렇군요. 변경하도록 할께요.

15. 4. 17., Changwoo Park <notifications@github.com>님이 작성:
> Windows의 한글 표기는 '윈도'이고, 1판에서도 '윈도'라고 표기했습니다. 찾아보니 빠트린 곳도 있네요.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/progit/progit2-ko/issues/20#issuecomment-93827210


-- 
- 최용재
- mage
- lnyarl

**Comment by lethee** [comment]
* run `git fetch`
 1. `git fetch`를 실행한다.
 2. `git fetch` 명령을 실행한다.

command와 공백으로 띄울 수 있어서 보기에 좋기에 개인적으로 2를 선호합니다.

**Comment by lethee** [comment]
commits 복수형
 1. 커밋들
 2. 커밋

소리내어 읽기에 아주 이상하지 않다면 '들' 을 뺀 2를 선호합니다.

**Comment by pismute** [comment]
`git fetch` 명령은 좋은 생각인 것 같습니다. :+1: 
`들`문제는 기준이 모호합니다. 한 번에 용어 정리하는 방식으로는 어렵지 않을까요.

**Comment by lnyarl** [comment]
저도 명령과 명령어를 섞어가면서 사용했습니다.
들은 전 안쓰려고 노력했습니다. 명시해야 한다면 '여러 커밋'이나 '이 모든 커밋'정도로 쓰는걸 좋아합니다.(하지만 다시
생각해보니 저도 '들'을 자주 쓴거같아요-_-a)

15. 4. 30., Changwoo Park <notifications@github.com>님이 작성:
> `git fetch` 명령은 좋은 생각인 것 같습니다. :+1:
> `들`문제는 기준이 모호합니다. 한 번에 용어 정리하는 방식으로는 어렵지 않을까요.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/progit/progit2-ko/issues/20#issuecomment-97474298


-- 
- 최용재
- mage
- lnyarl

**Comment by pismute** [comment]
기본 적으로 복수는 부사로 표현하는 게 좋다고 생각합니다. 내가 생각하는 `들`의 용법은 두 가지 입니다.

* 비꼴때 - `번역들은 좀 하시나들?`
* 복수를 표현하는 부사를 많이 써야할 때(`여러 ... 많은... 모두...여러...많은..모두 `) 단조로움을 회피하기 위해서 사용합니다.

Pro Git에서는 비꼴 일이 없으니, 내가 `들`을 쓴 것은 실수거나 위의 상황에서 입니다.

**Comment by pismute** [comment]
* [ ] Unstage 상태 => Unstated 상태.

**Comment by lethee** [comment]
* Working Directory - 작업 디렉토리

**Comment by pismute** [comment]
- [ ] Tracking branch - 트래킹 브랜치
- [ ] Remote tracking branch - 리모트 트래킹 브랜치
- [ ] Submodule - 서브모듈

**Comment by pismute** [comment]
명령어와 용어를 구분할 때, 그러니까 `git`과 `Git`을 구분할 때는 인용표기와 함께 하는게 좋을 것 같아요.
인용(?) 부호(``` ``'', ``, "", '' ```)가 없을 때는 용어로 보고 Git으로 하고 인용부호가 있을 때는 명령어라고 보고 `git`으로 하는 게 좋을 것 같아요. 반대로 명령어 인데 부호가 없으면 부호를 넣어주고 이름인데 부호가 있으면 빼줘야 겠죠.

**Comment by pismute** [comment]
- [ ] Reference - Refs, 레퍼런스(원래 둘 다 맞지만 Refs를 선호하는 걸로,,,더 짧으니까...)

**Comment by pismute** [comment]
이름은 그냥 영어로 표기하는 것은 어떨까요? 현재는 모든 표현이 혼재돼 있어요.
 - [ ] Windows, 윈도우, 윈도우즈, 윈도 - Windows
 - [ ] Mac, 맥 - Mac
 - [ ] Linux, 리눅스 - Linux

**Comment by lethee** [comment]
모든 리뷰와 upto-f61c801 끝나는대로 일괄 변경하겠습니다.

**Comment by lethee** [comment]
스냅 샷 - 스냅샷

**Comment by lethee** [comment]
#30 으로 Pull Request 열었습니다.

**Comment by lethee** [comment]
#30 merged

**Comment by pismute** [comment]
[ ] 다음과 - 아래와

**Comment by pismute** [comment]
이 이슈는 오늘 정래서 닫을 계획입니다. 빠진 것 있으면 메모해주세요.
다 적용하지 못할 것 같고 할 수 있는 것 하고 나머지는 정리해 두겠습니다.

**Comment by pismute** [comment]
아래 내용은 보류하기로 하고 확인하지 않았습니다:

- Workflow -> 워크플로우
- bundle - bundle(명령어일때), Bundle(번들로 만들어진 파일이나 그 개념을 나타낼때)
- rebase - Rebase
- push - Push
- git - Git
