### ISSUE TITLE
Atlas build is getting failure.

### ISSUE THREAD

**Issue by pismute** [progit/progit2-ko#57]
Hi @schacon, I need your help.

[Building of progit2-ko](https://progit.org/translations/lang/ko) has failed since July. The system complains nothing. I got success to build it with `bundle exec rake book:build` in my local. I could not find out why it fails.

**Comment by jaeguly** [comment]
Hi @schacon, I need your help too.

**Comment by jaeguly** [comment]
Hi @ben 
I need your help, please.

**Comment by pismute** [comment]
Fixed by #90
