### ISSUE TITLE
PDF 파일 생성시 문제

### ISSUE THREAD

**Issue by dksemfh** [progit/progit2-ko#66]
PDF 파일 생성시 이미지 파일이 보이지 않는 경우가 있습니다.

Figure 1. 로컬 버전 관리.     <----  이런 글자만 나오고 그림은 보이지 않습니다.

그리고 

01-introduction 에서 사용하는 'centralized.png' 파일명과
05-distributed-git 에서 사용하는 'centralized.png' 파일명이 같아서 
뒤에 파일로 표시됩니다.
영어 원본에서는 05-distributed-git 에서 사용하는 파일명이 'centralized_workflow.png' 으로 되어있습니다.

**Comment by pismute** [comment]
감사합니다. 

* `Figure 1. 로컬 버전 관리.`: 정말 그림이 누락 돼있습니다. 수정하겠습니다.
* `centralized.png` 문제도 정말 감사드립니다.

**Comment by pismute** [comment]
그림이 누락되는 문제는 pdf에서만 발생하는 문제인 것 같습니다. `Figure 1` 뿐만 아니라 다수 누락되고 있습니다. 아직 문제를 찾지 못했습니다. 감사합니다.

@lethee @lnyarl

**Comment by dksemfh** [comment]
pdf에서 이미지 누락은 이미지파일 문제인것 같습니다. 이미지 편집기에서 다시 저장해서(.png -> .png) pdf생성하면 잘 나옵니다.

**Comment by dksemfh** [comment]
원인은 png 파일의 alpha채널 때문입니다. 

https://github.com/prawnpdf/prawn/issues/783
https://github.com/prawnpdf/prawn/blob/master/lib/prawn/images/png.rb

**Comment by pismute** [comment]
prawn 버전이 달라지게된 이유가 CJK 때문입니다. 한글 폰트를 위해서 KaiGenGothic을 추가했고 이 과정에서 의존성이 asciidoc-pdf을 통헤서 prawn까지 영향을 끼치게 됐습니다. prawn을 낮추면 KaiGenGothic을 쓸 수 없습니다.

중국어 버전(progit2-zh)을 참고했는데, 지금 빌드해보니 중국어는 또 그림이 나옵니다. OTL,,, 

일본어는 KaiGenGothic을 추가하지 않았습니다. KaiGenGothic 없이 빌드하는 방법을 찾아보는 것도 방법이겠네요.

좀 더 살펴보겠습니다:)

**Comment by pismute** [comment]
중국어판의 경우 이전 버전의 이미지들입니다. 영문판에서 이미지 크기가 너무 크다고 줄였습니다(progit/progit2@3de8ef2). 이미지 파일은 영문판 기준으로 똑같이 맞추고 있습니다. png 파일의 alpha 채널 문제라고 볼 수도 있지만 png 파일을 직접 수정하고 싶지 않습니다.

저 이슈를 보면 png 파일을 가려받는 prawn 문제로 보는 것이 맞을 것 같습니다. 그리고 해결 된 것(prawnpdf/prawn#920) 같습니다. asciidoctor-pdf에서도 해결되면(asciidoctor/asciidoctor-pdf#257) 바로 적용하겠습니다.

prawn 소스로라도 빌드 해볼까 했는데 asciidoctor-pdf 패치가 필요합니다. 제가 루비를 몰라서 손댈 수가 없군요. 정말 감사드립니다.

**Comment by dksemfh** [comment]
1. 업데이트하면서 centralized_workflow.png 파일이 사라졌습니다.

2. 05-distributed-git > sections > contributing.asc 파일 내용 중에 
        //////////////////////////
       .`origin/master` 브랜치를 Merge 하고 난 후, John씨의 저장소.
       image::images/small-team-2.png[`origin/master` 브랜치를 Merge 하고 난 후, John씨의 저장소.]
   이미지 표시하는 곳이 있는데 이미지 파일명 뒤의 [ ] 안에 쉼표(,)가 있으면 이미지가 PDF에서 표시 되지 
  않습니다.   이런 곳이 위 부분과 아래 부분, 두곳이 있습니다.
  A-git-in-other-environments > sections > visualstudio.asc 파일의
      //////////////////////////
     .Visual Studio의 Git 센터, "Home" 뷰.
     image::images/vs-2.png[Visual Studio의 Git 센터, "Home" 뷰.]

**Comment by pismute** [comment]
정말 감사드립니다. 모두 놓치고 있었습니다.

**Comment by dksemfh** [comment]
prawn에서 png 처리 파일(png.rb)을 변경한 것입니다.
[png.rb.tar.gz](https://drive.google.com/open?id=0B7ws7n84mBy0Mi1YVXF6eTB5T2c)
[(prawnpdf/prawn#920)](https://github.com/prawnpdf/prawn/pull/920)로는 문제 해결이 안됐습니다.
중국어버전 이미지든, 영어버전 이미지든 잘 나옵니다.
다만 pdf에 표시 되는 이미지의 크기 조정은 어디서 하는지 더 찾아 봐얄것 같습니다.

수정해 주시느라 고생 많으시고 항상 감사합니다.

**Comment by dksemfh** [comment]
prawn에서 png 처리 파일을 수정했는데 링크해도 될지 모르겠네요. 일단은 링크해 봅니다. 
[png.rb 파일](https://drive.google.com/open?id=0B7ws7n84mBy0Mi1YVXF6eTB5T2c)

  문제 원인은 png 파일 타입에 있습니다. 타입이 3가지(gray, indexed, rgb)인데 중국어 버전은 rgb 타입이고, 영문 버전은 파일의 용량을 줄이기 위해서인듯 indexed 타입 입니다. 그런데 png를 처리하는 루틴에서 indexed 타입 파일을 처리하지 못해서 발생한 것입니다.

  링크된 파일을 다운해서 prawn이 설치된 폴더에 있는 png.rb파일을 대체하시면 됩니다. 제가 테스트 할 땐 잘 됐는데 다른 환경에서는 어떨지 모르겠습니다.

**Comment by pismute** [comment]
감사합니다. 부탁이 있는데 pismute@gmail.com으로 메일 좀 부탁드립니다.

**Comment by pismute** [comment]
@dksemfh 버전을 올려서 빌드하니 이미지 잘 나옵니다. 감사합니다.
