### ISSUE TITLE
데비안류 를 데비안계열로 하는 것은 어떨까요

### ISSUE THREAD

**Issue by jinto** [progit/progit2-ko#70]
안녕하세요. 의미있는 작업을 해주셔서 감사합니다.
문서를 읽다가 "데비안류" 라는 표현을 몇번 마주쳤습니다.
혹 기존 번역하신 분들간에 공유된 결정사항인지 궁금합니다.

```
CentOS나 Scientific Linux 같은 RHEL류(derivatives) 사용자
```

와 같은 문장은

``` 
CentOS나 Scientific Linux 같은 RHEL계열 사용자
```

라고 하면 더 좋지 않을까 의견 드립니다.

감사합니다.

**Comment by pismute** [comment]
안녕하세요. 정말 감사드립니다.

두 가지 아이디어로 어휘나 표현을 선택했습니다:

1. '가능한 짧은 표현'을 방향으로 번역을 했습니다. 의미가 통하면 짧은 표현을 선택했습니다. 한국어 실력 부족으로 간단한 규칙이 중요했습니다. 다른 어휘나 표현을 고를 때도 "가능한 짧은 표현"을 가장 중요하게 생각했습니다. 그런 이유로 "계열" 대신 "류"로 번역했습니다.

2. 잘못된 선택이 있으면 누군가 더 나은 표현으로 PR을 보내 줄 것이라고 생각했습니다(드디어, 너무 기뻐요. 만세~~). PR로 토론을 통해 반영하는 게 옳다고 생각하고 있습니다.

'계열'로 고쳐서 PR을 보내주시면 Merge 하겠습니다. 너무 기뻐서 바로 Merge하고 싶지만 몇 일 기다렸다 하겠습니다:)

의견 매우 감사합니다.
