### ISSUE TITLE
빌드시 그림이 import 되어 있지 않은 문제

### ISSUE THREAD

**Issue by damho1104** [progit/progit2-ko#88]
알려주신대로 빌드하고 나온 결과물을 봤을때 각 그림이 추가되어 있질 않습니다.
그림을 첨부합니다.
![image](https://user-images.githubusercontent.com/9390065/34191303-4c225d40-e589-11e7-9918-4c60e40121df.png)

**Comment by Danpatpang** [comment]
링크 또한 import되지 않는 것 같습니다.

**Comment by lethee** [comment]
확인하겠습니다.

**Comment by lethee** [comment]
현재 최신 빌드 방법으로 이미지가 PDF에 잘 import 되는 것을 확인했습니다.
