### ISSUE TITLE
Automatic publishing of PDF and epub

### ISSUE THREAD

**Issue by jnavila** [progit/progit2-ko#89]
Hi all,

I'm in the process of making an automatic publication of the book on git-scm.com, using asciidoctor and Travis-CI for generating the PDF and epub.

This rework requires to move files around, change how cross-refs are done and change build script. This is quite disruptive and would cause conflicts with ongoing changes.

Please ping me when the repo is idle, so that I can make the transition before you guys restart your work.

Thanks,

**Comment by pismute** [comment]
Hi,

Thank you for the process.
The repo is rather idle, please do it.

Best Regards,
