### ISSUE TITLE
2.2장 Recording Changes to the Repository 그림 원본과의 차이

### ISSUE THREAD

**Issue by LeeJaeilHan** [progit/progit2-ko#97]
https://git-scm.com/book/no-nb/v1/Grunnleggende-Git-Recording-Changes-to-the-Repository
### 원본 그림
![image](https://user-images.githubusercontent.com/33744302/62103316-0ef28b80-b2d7-11e9-9f33-87a64777d970.png)

### 프로git 2판 그림
![image](https://user-images.githubusercontent.com/33744302/62103137-79ef9280-b2d6-11e9-9bab-07e8dcc9d394.png)

원본 그림의 의미가 더 정확한 것 같습니다~!

**Comment by lethee** [comment]
알려주신 원본 그림은 1판의 내용이며, 2판에서는 영문에서도 동일하게 아래 그림으로 변경되었습니다.

https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository
