### ISSUE TITLE
깃북 링크 수정(영문 페이지 -> 한글 페이지)

### ISSUE THREAD

**Issue by Reevid** [progit/progit2-ko#98]
https://github.com/progit/progit2-ko#pro-git-2%ED%8C%90 에 포함되어 있는 http://git-scm.com/book 는 한국어로 되어 있는 페이지( https://git-scm.com/book/ko/v2 )로 연결되는 것이 좋지 않을까요?

**Comment by lethee** [comment]
감사합니다. 확인 후 수정하겠습니다.

**Comment by lethee** [comment]
http://git-scm.com/book URL은 모든 언어, 모든 버전의 책에 대한 대표 링크로 생각하여 URL을 지금처럼 유지하려고 합니다.
